version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: GradingGrinchesDemo
    networks:
      - react-node

  backend:
    build: ./backend
    ports:
      - "8888:8888"
    container_name: GradingGrinchesDemo
    networks:
      - react-node
      - node-network

  db:
    image: mongo:latest
    ports:
    - "27017:27017"
    container_name: GradingGrinchesDemo
    networks:
      - node-network

networks:
  node-network:
  react-node: