name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo systemctl restart docker
    - run: sudo docker kill $(sudo docker ps -q) && sudo docker rm $(sudo docker ps -a -q) && sudo docker volume rm $(sudo docker volume ls -q) && sudo docker rmi $(sudo docker images -q)
    - run: sudo systemctl daemon-reload
    - run: sudo systemctl restart docker-compose

            
