name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./backend
    - run: pwd
    - run: npm ci
    - run: cd ..
    - run: cd ./frontend
    - run: pwd
    - run: npm ci
    - run: sudo systemctl daemon-reload
    - run: sudo systemctl restart backend
    - run: sudo systemctl restart frontend

            
