name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance IP or domain name
          username: ${{ secrets.EC2_USERNAME }} # EC2 instance username (usually ec2-user for Amazon Linux)
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Private SSH key
          script: |
            cd /workplace/GradingGrinchesDemo/
            git pull origin main # Pull the latest changes from GitHub
            cd /backend/
            npm install
            sudo systemctl restart backend
            cd ..
            cd /frontend/
            npm install
            sudo systemctl restart frontend

            
